{
 "title": "Overview",
 "tags": [
  "influxdb",
  "luxardo_labs",
  "weatherflow-collector"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "data_source_influxdb", "label": "Data Source InfluxDB", "query": "influxdb" },
   { "name": "data_source_websocket", "label": "Data Source Websocket", "query": "golioth-websocket-datasource" },
   {
    "name": "station_name",
    "label": "Station Name",
    "query": "SHOW TAG VALUES WITH KEY = \"station_name\""
   },
   {
    "name": "source",
    "label": "Streaming Source",
    "query": "collector_udp,collector_websocket"
   },
   {
    "name": "collector_type",
    "label": "Collector Type",
    "query": "SHOW TAG VALUES WITH KEY = \"collector_type\""
   },
   {
    "name": "station_time_zone",
    "label": "Station Time Zone",
    "query": "SHOW TAG VALUES WITH KEY = \"station_time_zone\" WHERE \"station_name\" =~ /^$station_name$/"
   },
   {
    "name": "station_id",
    "label": "Station ID",
    "query": "SHOW TAG VALUES WITH KEY = \"station_id\"  WHERE \"station_name\" =~ /^$station_name$/"
   },
   {
    "name": "device_id",
    "label": "Device ID",
    "query": "SHOW TAG VALUES WITH KEY = \"device_id\"  WHERE \"station_name\" =~ /^$station_name$/"
   }
  ]
 },
 "panels": [
  {
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://labs.lux4rd0.com/wp-content/uploads/2021/05/weatherflow_collector_header.png\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wind Speed",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].wind_direction",
       "language": "jsonpath",
       "name": "Wind Direction"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].wind_speed",
       "language": "jsonpath",
       "name": "Wind Speed"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].longitude",
       "language": "jsonpath",
       "name": "Longitude"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].latitude",
       "language": "jsonpath",
       "name": "Latitude"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].timestamp",
       "language": "jsonpath",
       "name": "Time Stamp"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].station_name",
       "language": "jsonpath",
       "name": "Station Name"
      }
     ],
     "path": "$source/$device_id"
    }
   ]
  },
  {
   "title": "$station_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "station_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Forecast High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forecast High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "query": "SELECT last(\"air_temp_high\") * 9/5 + 32 FROM \"weatherflow_forecast_daily\" WHERE (\"station_name\" =~ /^$station_name$/) AND $timeFilter GROUP BY time(1d) tz('$tz')",
     "select": [
      [
       { "params": [ "air_temp_high" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "collector_forecast" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Observed High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Observed High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "primary" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Forecast Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forecast High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "query": "SELECT last(\"air_temp_high\") * 9/5 + 32 FROM \"weatherflow_forecast_daily\" WHERE (\"station_name\" =~ /^$station_name$/) AND $timeFilter GROUP BY time(1d) tz('$tz')",
     "select": [
      [
       { "params": [ "air_temp_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "collector_forecast" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Observed Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "Observed Low",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "primary" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].timestamp",
       "language": "jsonpath",
       "name": "",
       "type": "time"
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].wind_speed",
       "language": "jsonpath",
       "name": "",
       "type": "number"
      }
     ],
     "path": "$source/$device_id"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].timestamp",
       "language": "jsonpath",
       "name": ""
      },
      {
       "jsonPath": "$.rapid_wind['$source']['$station_name'].wind_direction",
       "language": "jsonpath",
       "name": "",
       "type": "number"
      }
     ],
     "path": "$source/$device_id"
    }
   ]
  },
  {
   "title": "Station Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Station Pressure",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "station_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .0295301" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  },
  {
   "title": "Chance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Chance",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "select": [
      [
       { "params": [ "precip_probability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "collector_forecast" }
     ],
     "tz": "$station_time_zone"
    }
   ]
  }
 ]
}