{
 "title": "Collector Duration",
 "tags": [
  "weatherflow-collector",
  "influxdb"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station_name",
    "label": "Station Name",
    "query": "SHOW TAG VALUES WITH KEY = \"station_name\""
   },
   {
    "name": "tz",
    "label": "Time Zone",
    "query": "SHOW TAG VALUES WITH KEY = \"timezone\""
   },
   {
    "name": "interval",
    "query": "7d,2d,1d,12h,6h,4h,2h,1h,30m,15m,10m,5m,2m,1m"
   }
  ]
 },
 "panels": [
  {
   "title": "Forecast Build Duration - Daily",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_forecast_daily",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Forecast Build Duration - Hourly",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_forecast_hourly",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Rest Observations Fetch Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Remote Import",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "local-udp" }
     ],
     "tz": "$tz"
    }
   ]
  }
 ]
}