{
 "title": "System Stats (w/Loki)",
 "description": "WeatherFlow Collector provides multiple ways of collecting data from the WeatherFlow Tempest, Air, and Sky weather systems. These Grafana dashboards offer visualizations in real-time for current conditions, derived metrics, and forecasting.",
 "tags": [
  "weatherflow-collector",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "station_name",
    "label": "Station Name",
    "query": "SHOW TAG VALUES WITH KEY = \"station_name\""
   },
   {
    "name": "tz",
    "label": "Time Zone",
    "query": "SHOW TAG VALUES WITH KEY = \"timezone\""
   },
   {
    "name": "collector_type",
    "label": "Collector Type",
    "query": "SHOW TAG VALUES WITH KEY = \"collector_type\""
   },
   {
    "name": "source",
    "label": "Source",
    "query": "SHOW TAG VALUES WITH KEY = \"source\""
   },
   {
    "name": "collector_key",
    "label": "Collector Key",
    "query": "SHOW TAG VALUES WITH KEY = \"collector_key\""
   },
   {
    "name": "host_hostname",
    "label": "Host",
    "query": "select DISTINCT(\"host_hostname\") from (select \"host_hostname\",\"cpu_soft\" from \"weatherflow_system_stats\" WHERE $timeFilter)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "7d,2d,1d,12h,6h,4h,2h,1h,30m,15m,10m,5m,2m,1m,10s"
   },
   {
    "name": "collector_type_logs",
    "label": "Collector Type Logs",
    "query": "local-udp,remote-forecast,remote-rest,remote-socket"
   }
  ]
 },
 "panels": [
  { "title": "Collector Duration Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Forecast Build Duration - Daily (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "forecast_daily_build" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Forecast Build Duration - Hourly (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "forecast_hourly_build" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Rest Observations Fetch Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "observations" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Health Check Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_collector_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "collector_key" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "health-check" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "health_check" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Host Performance Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_collector_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "collector_key" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "host-performance" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "host_performance" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Loki Backend Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_collector_key - $tag_collector_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "collector_key" ], "type": "tag" },
      { "params": [ "collector_type" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" },
      { "condition": "AND", "key": "duration_type", "operator": "=", "value": "loki_push" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Collector Stats - $collector_key",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "collector_key"
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"weatherflow_system_stats\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "cpu_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "IO Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"weatherflow_system_stats\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "loadavg_one" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_five" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_fifteen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Process CPU Usage (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_sysperf_command",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sysperf_command" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "host-performance" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "sysperf_type", "operator": "=", "value": "process_utilization" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Netstat (Container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_netstat_app - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "netstat_app" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"weatherflow_system_stats\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "netstat_closewait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Close Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Established" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_finwait2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Finwait2" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_listen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Listen" ], "type": "alias" }
      ],
      [
       { "params": [ "netstat_timewait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Timewait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "sysperf_type", "operator": "=", "value": "netstat" }
     ]
    }
   ]
  },
  {
   "title": "Processes (Container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"weatherflow_system_stats\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "processes_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "processes_zombie" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Zombie" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_system_stats",
     "query": "SELECT mean(\"cpu_idle\") AS \"Idle\", mean(\"cpu_iowait\"), mean(\"cpu_sys\"), mean(\"cpu_usr\") FROM \"weatherflow_system_stats\" WHERE (\"host_hostname\" = 'docker02.tylephony.com') AND $timeFilter GROUP BY time($__interval), \"host_hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_buffers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffers" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_cache" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_shared" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" }
     ]
    }
   ]
  },
  {
   "title": "Collector Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_health_check_collector_type",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "health_check_collector_type" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_events",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "health_check_collector_type", "operator": "=~", "value": "/^$collector_type$/" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "healthcheck" }
     ]
    }
   ]
  },
  {
   "title": "Collector Starts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_collector_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "collector_type" ], "type": "tag" },
      { "params": [ "collector_key" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_events",
     "select": [
      [
       { "params": [ "time_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "process_start" },
      { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Collector Start Time",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "alias": "$tag_collector_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "collector_type" ], "type": "tag" }
     ],
     "measurement": "weatherflow_system_events",
     "select": [
      [
       { "params": [ "time_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host_hostname", "operator": "=~", "value": "/^$host_hostname$/" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "collector" },
      { "condition": "AND", "key": "collector_key", "operator": "=~", "value": "/^$collector_key$/" },
      { "condition": "AND", "key": "event", "operator": "=", "value": "process_start" }
     ]
    }
   ]
  },
  {
   "title": "Loki Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs from $collector_type_logs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (collector_type, station_name) (bytes_over_time({app=\"weatherflow-collector\",collector_type=~\"$collector_type_logs\", station_name=~\"$station_name\"}[$__interval]))",
       "legendFormat": "{{station_name}} - {{collector_type}}"
      }
     ]
    },
    {
     "title": "Logs from $collector_type_logs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
     "repeat": "collector_type_logs",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (station_name, host_hostname) (count_over_time({app=\"weatherflow-collector\",collector_type=~\"$collector_type_logs\", station_name=~\"$station_name\"}[$__interval]))",
       "legendFormat": "{{station_name}} - {{host_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Import",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Import",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$tag_station_name - $tag_collector_type",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "station_name" ], "type": "tag" },
        { "params": [ "collector_type" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "weatherflow_system_stats",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
        { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" },
        { "condition": "AND", "key": "source", "operator": "=", "value": "import" }
       ],
       "tz": "$tz"
      },
      {
       "alias": "$tag_station_name - $tag_collector_type: Metrics",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "station_name" ], "type": "tag" },
        { "params": [ "collector_type" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "weatherflow_system_stats",
       "select": [
        [
         { "params": [ "import_metrics" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
        { "condition": "AND", "key": "collector_type", "operator": "=~", "value": "/^$collector_type$/" },
        { "condition": "AND", "key": "source", "operator": "=", "value": "import" }
       ],
       "tz": "$tz"
      }
     ]
    }
   ]
  }
 ]
}