{
 "title": "Device Details",
 "tags": [
  "weatherflow-collector",
  "influxdb"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hub_sn",
    "label": "Hub",
    "query": "SHOW TAG VALUES WITH KEY = \"hub_sn\"  WHERE \"collector_type\" =~ /^$collector_type$/"
   },
   {
    "name": "serial_number",
    "query": "SHOW TAG VALUES WITH KEY = \"serial_number\"  WHERE \"hub_sn\" =~ /^$hub_sn$/ and \"collector_type\" =~ /^$collector_type$/"
   },
   { "name": "collector_type", "query": "local-udp" }
  ]
 },
 "panels": [
  { "title": "$hub_sn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hub_sn" },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "$tag_hub_sn -> WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hub_sn" ], "type": "tag" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "$tag_serial_number -> Hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_number" ], "type": "tag" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Hub -> $tag_serial_number",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_number" ], "type": "tag" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT mean(\"hub_rssi\") FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/ AND \"collector_type\" =~ /^$collector_type$/) AND $timeFilter GROUP BY time($__interval), \"serial_number\"",
     "select": [
      [
       { "params": [ "hub_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Status Hub - $hub_sn",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Firmware Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "firmware_revision" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Radio Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "radio_stats_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Radio Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "radio_stats_radio_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Reboot Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "radio_stats_reboot_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "I2C Bus Count Error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       {
        "params": [
         "radio_stats_i2c_bus_error_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_hub_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Status - $serial_number",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "repeat": "serial_number",
   "targets": [
    {
     "alias": "Firmware Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "firmware_revision" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Hub RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "hub_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Sensor Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Sensors OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 20 },
   "repeat": "obs_serial_number",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Lightning Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Lightning Noise",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Lightning Disturber",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "RH Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Precipitation Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  },
  {
   "title": "Light/UV Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "weatherflow_device_status",
     "query": "SELECT COUNT(DISTINCT(\"sensor_status\")) FROM \"weatherflow_device_status\" WHERE (\"serial_number\" =~ /^$serial_number$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sensor_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "serial_number", "operator": "=~", "value": "/^$serial_number$/" },
      { "condition": "AND", "key": "hub_sn", "operator": "=~", "value": "/^$hub_sn$/" }
     ]
    }
   ]
  }
 ]
}