{
 "title": "Collector Duration",
 "tags": [
  "weatherflow-collector",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station_name",
    "label": "Station Name",
    "query": "SHOW TAG VALUES WITH KEY = \"station_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Forecast Build Duration - Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_forecast_daily",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Forecast Build Duration - Hourly",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_forecast_hourly",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Rest Observations Fetch Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_station_name",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "station_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ]
    }
   ]
  }
 ]
}